### ISSUE TITLE
not work in python 3.10

### ISSUE THREAD

**Issue by kingstone101** [NVIDIA/pix2pixHD#335]
CustomDatasetDataLoader
Traceback (most recent call last):
  File "C:\Users\GAMER\Desktop\pix2pixHD-master\train.py", line 43, in <module>
    data_loader = CreateDataLoader(opt)
  File "C:\Users\GAMER\Desktop\pix2pixHD-master\data\data_loader.py", line 6, in CreateDataLoader
    data_loader.initialize(opt)
  File "C:\Users\GAMER\Desktop\pix2pixHD-master\data\custom_dataset_data_loader.py", line 20, in initialize
    self.dataset = CreateDataset(opt)
  File "C:\Users\GAMER\Desktop\pix2pixHD-master\data\custom_dataset_data_loader.py", line 7, in CreateDataset
    from data.aligned_dataset import AlignedDataset
  File "C:\Users\GAMER\Desktop\pix2pixHD-master\data\aligned_dataset.py", line 2, in <module>
    from data.base_dataset import BaseDataset, get_params, get_transform, normalize
  File "C:\Users\GAMER\Desktop\pix2pixHD-master\data\base_dataset.py", line 3, in <module>
    import torchvision.transforms as transforms
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\__init__.py", line 6, in <module>
    from torchvision import _meta_registrations, datasets, io, models, ops, transforms, utils
  File "C:\Users\GAMER\AppData\Local\Programs\Python\Python310\lib\site-packages\torchvision\_meta_registrations.py", line 163, in <module>
    @torch._custom_ops.impl_abstract("torchvision::nms")
AttributeError: module 'torch._custom_ops' has no attribute 'impl_abstract'
